### ISSUE TITLE
Missing lint packages

### ISSUE THREAD

**Issue by tavurth** [i18next/i18next-localstorage-backend#2]
After working with this package today I found this issue which would be helpful for future development:

#### Adding the script:
```json
"lint": "eslint ./src/*"
```
to the `package.json` eslint fails to run.

#### Eslint cites:
```
Tavurth i18next-localstorage-backend > yarn lint
yarn lint v0.18.1
$ eslint ./src/*

Oops! Something went wrong! :(

ESLint couldn't find the plugin "eslint-plugin-jsx-a11y". This can happen for a couple different reasons:
```

And numerous other missing packages. 

#### Perhaps we could add these to the `package.json`?

`eslint-plugin-jsx-a11y`
`eslint-plugin-react`
`eslint-plugin-import`

#### Which then fails with:

```

$ eslint ./src/*
/Users/Tavurth/projects/i18next-localstorage-backend/node_modules/eslint-config-airbnb-base/rules/style.js:
	Configuration for rule "no-restricted-syntax" is invalid:
	Value "[object Object]" must be an enum value.

Referenced from: /Users/Tavurth/projects/i18next-localstorage-backend/node_modules/eslint-config-airbnb-base/index.js
Referenced from: airbnb
Referenced from: /Users/Tavurth/projects/i18next-localstorage-backend/.eslintrc
Error: /Users/Tavurth/projects/i18next-localstorage-backend/node_modules/eslint-config-airbnb-base/rules/style.js:
	Configuration for rule "no-restricted-syntax" is invalid:
	Value "[object Object]" must be an enum value.

Referenced from: /Users/Tavurth/projects/i18next-localstorage-backend/node_modules/eslint-config-airbnb-base/index.js
Referenced from: airbnb
Referenced from: /Users/Tavurth/projects/i18next-localstorage-backend/.eslintrc
    at validateRuleOptions (/Users/Tavurth/projects/i18next-localstorage-backend/node_modules/eslint/lib/config/config-validator.js:109:15)
    at Object.keys.forEach.id (/Users/Tavurth/projects/i18next-localstorage-backend/node_modules/eslint/lib/config/config-validator.js:156:13)
    at Array.forEach (<anonymous>)
    at Object.validate (/Users/Tavurth/projects/i18next-localstorage-backend/node_modules/eslint/lib/config/config-validator.js:155:35)
    at load (/Users/Tavurth/projects/i18next-localstorage-backend/node_modules/eslint/lib/config/config-file.js:529:19)
    at configExtends.reduceRight (/Users/Tavurth/projects/i18next-localstorage-backend/node_modules/eslint/lib/config/config-file.js:391:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/Tavurth/projects/i18next-localstorage-backend/node_modules/eslint/lib/config/config-file.js:362:28)
    at load (/Users/Tavurth/projects/i18next-localstorage-backend/node_modules/eslint/lib/config/config-file.js:536:22)
    at configExtends.reduceRight (/Users/Tavurth/projects/i18next-localstorage-backend/node_modules/eslint/lib/config/config-file.js:391:36)
error Command failed with exit code 1.
```

#### Which was fixed by:

Upgrading `eslint` to `4.x`.

#### Which fails with:

```
Error: Cannot find module 'escope'
```

Finally, we can run `yarn lint`.

#### The script then fails with:

```
Tavurth i18next-localstorage-backend > yarn lint
yarn lint v0.18.1
$ eslint ./src/*

/Users/Tavurth/projects/i18next-localstorage-backend/src/index.js
   5:9   error  'window' is not defined                                 no-undef
   7:9   error  'window' is not defined                                 no-undef
  14:9   error  'window' is not defined                                 no-undef
  16:16  error  'window' is not defined                                 no-undef
  45:3   error  Expected to return a value at the end of method 'read'  consistent-return
  46:11  error  'store' is assigned a value but never used              no-unused-vars
  49:10  error  'window' is not defined                                 no-undef
  74:9   error  'window' is not defined                                 no-undef
  75:7   error  Assignment to property of function parameter 'data'     no-param-reassign
  79:9   error  Assignment to property of function parameter 'data'     no-param-reassign

/Users/Tavurth/projects/i18next-localstorage-backend/src/utils.js
   1:5   error    'arr' is never reassigned. Use 'const' instead                                                                                                                         prefer-const
   2:5   error    'each' is never reassigned. Use 'const' instead                                                                                                                        prefer-const
   3:5   error    'slice' is never reassigned. Use 'const' instead                                                                                                                       prefer-const
   3:5   error    Use object destructuring                                                                                                                                               prefer-destructuring
   6:24  error    Use the rest parameters instead of 'arguments'                                                                                                                         prefer-rest-params
   6:39  error    Unexpected function expression                                                                                                                                         prefer-arrow-callback
   6:39  warning  Unexpected unnamed function                                                                                                                                            func-names
   6:47  error    Missing space before function parentheses                                                                                                                              space-before-function-paren
   8:7   error    for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array  no-restricted-syntax
   8:12  error    Unexpected var, use let or const instead                                                                                                                               no-var
   8:12  error    All 'var' declarations must be at the top of the function scope                                                                                                        vars-on-top
   9:38  error    Assignment to property of function parameter 'obj'                                                                                                                     no-param-reassign
  17:24  error    Use the rest parameters instead of 'arguments'                                                                                                                         prefer-rest-params
  17:39  warning  Unexpected unnamed function                                                                                                                                            func-names
  17:39  error    Unexpected function expression                                                                                                                                         prefer-arrow-callback
  17:47  error    Missing space before function parentheses                                                                                                                              space-before-function-paren
  19:7   error    The body of a for-in should be wrapped in an if statement to filter unwanted properties from the prototype                                                             guard-for-in
  19:7   error    for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array  no-restricted-syntax
  19:12  error    Unexpected var, use let or const instead                                                                                                                               no-var
  19:12  error    All 'var' declarations must be at the top of the function scope                                                                                                        vars-on-top
  20:9   error    Assignment to property of function parameter 'obj'                                                                                                                     no-param-reassign
  28:1   error    Expected indentation of 2 spaces but found 1 tab                                                                                                                       indent
  28:2   error    Unexpected tab character                                                                                                                                               no-tabs
  28:2   error    Unexpected var, use let or const instead                                                                                                                               no-var
  29:1   error    Expected indentation of 2 spaces but found 1 tab                                                                                                                       indent
  29:2   error    Unexpected tab character                                                                                                                                               no-tabs
  29:9   warning  Unexpected unnamed function                                                                                                                                            func-names
  29:17  error    Missing space before function parentheses                                                                                                                              space-before-function-paren
  30:1   error    Expected indentation of 4 spaces but found 2 tabs                                                                                                                      indent
  30:2   error    Unexpected tab character                                                                                                                                               no-tabs
  30:3   error    Split 'var' declarations into multiple statements                                                                                                                      one-var
  30:3   error    Unexpected var, use let or const instead                                                                                                                               no-var
  30:23  error    Expected variable declaration to be on a new line                                                                                                                      one-var-declaration-per-line
  30:30  error    Use the rest parameters instead of 'arguments'                                                                                                                         prefer-rest-params
  31:1   error    Expected indentation of 4 spaces but found 2 tabs                                                                                                                      indent
  31:2   error    Unexpected tab character                                                                                                                                               no-tabs
  31:3   error    Unexpected var, use let or const instead                                                                                                                               no-var
  31:15  warning  Unexpected unnamed function                                                                                                                                            func-names
  31:23  error    Missing space before function parentheses                                                                                                                              space-before-function-paren
  32:1   error    Expected indentation of 6 spaces but found 3 tabs                                                                                                                      indent
  32:2   error    Unexpected tab character                                                                                                                                               no-tabs
  33:1   error    Expected indentation of 6 spaces but found 3 tabs                                                                                                                      indent
  33:2   error    Unexpected tab character                                                                                                                                               no-tabs
  34:1   error    Expected indentation of 4 spaces but found 2 tabs                                                                                                                      indent
  34:2   error    Unexpected tab character                                                                                                                                               no-tabs
  35:1   error    Expected indentation of 4 spaces but found 2 tabs                                                                                                                      indent
  35:2   error    Unexpected tab character                                                                                                                                               no-tabs
  35:3   error    Unexpected var, use let or const instead                                                                                                                               no-var
  36:1   error    Expected indentation of 4 spaces but found 2 tabs                                                                                                                      indent
  36:2   error    Unexpected tab character                                                                                                                                               no-tabs
  37:1   error    Expected indentation of 4 spaces but found 2 tabs                                                                                                                      indent
  37:2   error    Unexpected tab character                                                                                                                                               no-tabs
  38:1   error    Expected indentation of 4 spaces but found 2 tabs                                                                                                                      indent
  38:2   error    Unexpected tab character                                                                                                                                               no-tabs
  39:1   error    Expected indentation of 2 spaces but found 1 tab                                                                                                                       indent
  39:2   error    Unexpected tab character                                                                                                                                               no-tabs
  40:2   error    Unnecessary semicolon                                                                                                                                                  no-extra-semi

✖ 67 problems (63 errors, 4 warnings)
  29 errors, 0 warnings potentially fixable with the `--fix` option.

error Command failed with exit code 1.
```

**Comment by jamuhl** [comment]
will see if i could update to be on par with https://github.com/i18next/i18next - but not high on my prio list as i do not rely on eslint anymore (not to useful honestly when working alone on a project).

**Comment by tavurth** [comment]
Is there a reason this was closed? I've added a PR which fixes your issue

**Comment by tavurth** [comment]
https://github.com/i18next/i18next-localstorage-backend/pull/6

**Comment by jamuhl** [comment]
I'm not sure what the benefit of this PR is? The code is working. This module is so tiny - if i really update those eslint stuff  (which i personally do not need - as started using prettier some time ago) i would level this up to the same standards used in the i18next repo: https://github.com/i18next/i18next but doing so would mean to also update all other repos (xhr-backend,browser-language detector,...)

**Comment by tavurth** [comment]
> not to useful honestly when working alone on a project
One benefit of the PR would be to other developers who want to work with you.
Another benefit of the PR would be a more robust code base. Currently the code base provided here is rather buggy, and crashes node when used with SSR. (See the 67 eslint errors)

If you don't intend to use eslint or to fix these bugs in future, I would suggest removing it from your `package.json` file, and perhaps mention in the `package.json` that your code is not SSR ready.

> doing so would mean to also update all other repos
Perhaps only updating one at a time, (when PRs become available) would be preferable to not updating at all.

**Comment by jamuhl** [comment]
this is a clientside repo using localstorage -> for sure this can't be used for SSR on serverside (there is no localstorage on server!!!) you will either add a fs-backend, one of the db-backends or a remote-backend

**Comment by tavurth** [comment]
The problem here is not that SSR is broken, it's that your module is poorly written, without a proper package.json, or consistent tab indentation (4 different tab indentations are used in these two files alone).

If your module is really an important part of the react-i18next ecosystem, you should update it to avoid losing face from such a shoddy attempt at a tech implementation.

**Comment by jamuhl** [comment]
i maintain i18next, react-i18next. so if my shoddy tech implementation powers thousand of sites - enables creation of millions in business revenue - while i work for free - i can live with using my face. I not at least care about spaces or tabs or semicolons or not - i care about business enabling.
